### ISSUE TITLE
OpenMVG

### ISSUE THREAD

**Issue by surberj** [surberj/Vision#72]
Lucas demonstrated on the data of 20160518 flight 0011, that the openMVG library produces pretty nice 3D structure from motion results for the Irchel data:

![openmvg_20160518](https://cloud.githubusercontent.com/assets/9253897/15816220/1ca28c6a-2bd2-11e6-8dd7-d4ee603c7eb8.png)

The point cloud out of the openMVG pipeline is denser and more accurate in "depth" (world-z) than the OKVIS point cloud (with two drawbacks - more outliers and no scale estimation). The result demonstrates that we should be able to get "better" point clouds out of the data than what I use as reference map at the moment.

Now there is the question how to use the results. I can see different ways:
1) Only for visualization --> Leave the system as it is but use the openMVG map within the rviz visualization
2) Study the openMVG code and modify OKVIS to a "offline, sequentialSfM" version. In ideal case this should leed to a scale consistent, outlier-"free" and more consistent (mainly in depth) reference map.  
3) Modify the openMVG code to describe the points by BRISK features (we need the customized OKVIS 48byte features) and create the reference map with openMVG.

I would best like to try out option 2, as it does not need manual scale estimation but still could give resonable improvement to the reference map.

**Comment by pmoulon** [comment]
Hi @surberj 
Just saw that you was doing experiments with OpenMVG to build some MAPS!

What you can do also, is to load the resulting map in your system, extract some features within your library and robustly triangulate them.

Doing 2) is reinventing the wheel, why do you need to spend time to rewrite something that is already working.
Doing 3) Should be fast, you just need to add new region type (for the Brisk feature), then you can use your own feature/descriptor extractor or use the one from opencv.

Some outlier can be easily removed if you consider tracks with a length >=3.

If you have some scale information, you can simply load the openMVG sfm scene and rescale it.

Would be happy to continue the discussion :+1:

**Comment by surberj** [comment]
Hi @pmoulon 
Thank you for your comment! I worked the last days on a presentation, excuse me for my late response. The good thing about the way I created my maps so far (with something similar to https://github.com/ethz-asl/okvis), is, that we include high quality IMU measurements between the image frames into the optimization (we minimize reprojection and IMU error terms). Moreover, there is a meaningful heuristic implemented, which selects frames out of the sequence and marginalizes out frames in between.
The bad thing about it, is, that the code is not optimized for structure-from-motion but rather for real-time localization and mapping, which means that data management gets bad for larger maps (everything is handled within main memory, all tracks are associated with the frames themselves). 

Do you know if there are plans in openMVG to include IMU measurements into the structure-from-motion pipeline? Either directly into the optimization or in a post processing step to align the map with gravity and support scale?

Thanks for your inputs!

**Comment by pmoulon** [comment]
Thanks for your answer.
No worries about the delay. One day is better than never ;-)
I plan to add the support of prior (position, rotation) to OpenMVG but since there is many ways to use those prior, I want to go into this task step by step.

I mean you can use those data (depending their quality) as trusted (used as direct global value), or they can be used a relative information in order to make the graph optimization stronger (according user weight confidence).

I would be very happy to make experiments with you if you can share some tiny dataset or point me some dataset we can play with ;-)

We can first work on alignment and scale if you want!
=> If you have two reconstructions with corresponding camera positions (two different coordinates system), the openMVG API is already able to perform the registration.

Discussion about how handling IMU data as residual cost function would be interesting too since I have not yet experience with it.

Let's continue the discussion here or by email.

PS: Moreover, using matches constrained by a homography can limits the number of outliers in your scenes, since your camera motion is small (main_ComputeMatches -g h, then rename matches.h.bin to the desired one (matches.e.bin or matches.h.bin).
